(function () {
    'use strict';
    document.addEventListener('DOMContentLoaded', function () {
        var input = document.getElementById('skillInput'), add = document.getElementById('addSkillButton'), list = document.getElementById('skillsList'), empty = document.getElementById('skillsEmpty'), error = document.getElementById('skillError'), count = document.getElementById('skillsCount'), countLabel = document.getElementById('skillsCountLabel'), save = document.getElementById('saveSkillsButton'), message = document.getElementById('skillsSaveMessage');
        var skills = ['HTML', 'CSS', 'JavaScript', 'ASP.NET'];
        function render() { list.innerHTML = ''; skills.forEach(function (skill, index) { var chip = document.createElement('div'); chip.className = 'student-skill-chip'; chip.innerHTML = '<span>' + skill + '</span><button type="button" aria-label="Remove ' + skill + '" data-index="' + index + '"><i class="fa-solid fa-xmark"></i></button>'; list.appendChild(chip); }); empty.style.display = skills.length ? 'none' : 'block'; count.textContent = skills.length; countLabel.textContent = skills.length; document.querySelectorAll('#suggestedSkills button').forEach(function (button) { button.classList.toggle('is-added', skills.indexOf(button.dataset.skill) !== -1); }); }
        function addSkill(value) { var skill = (value || '').trim(); error.textContent = ''; if (!skill) { error.textContent = 'Please enter a skill.'; return; } if (skills.some(function (item) { return item.toLowerCase() === skill.toLowerCase(); })) { error.textContent = 'This skill is already added.'; input.focus(); return; } skills.push(skill); input.value = ''; render(); input.focus(); }
        add.addEventListener('click', function () { addSkill(input.value); }); input.addEventListener('keydown', function (event) { if (event.key === 'Enter') { event.preventDefault(); addSkill(input.value); } }); list.addEventListener('click', function (event) { var button = event.target.closest('button[data-index]'); if (!button) return; skills.splice(Number(button.dataset.index), 1); render(); }); document.querySelectorAll('#suggestedSkills button').forEach(function (button) { button.addEventListener('click', function () { addSkill(button.dataset.skill); }); }); save.addEventListener('click', function () { message.textContent = 'Skills saved successfully.'; setTimeout(function () { message.textContent = ''; }, 3000); }); render();
    });
}());
