//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net
{
    public partial class stories
    {
        protected global::System.Web.UI.WebControls.ImageButton ImageButton1;
        protected global::System.Web.UI.WebControls.TextBox TextBox1;
    }
}
