IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'internship')
BEGIN
    CREATE TABLE internship (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        CompanySessionEmail NVARCHAR(100),
        Title NVARCHAR(200),
        Domain NVARCHAR(100),
        Description NVARCHAR(MAX),
        InternshipType NVARCHAR(50),
        WorkMode NVARCHAR(50),
        Location NVARCHAR(100),
        StartDate NVARCHAR(50),
        EndDate NVARCHAR(50),
        Duration NVARCHAR(50),
        WorkingHours NVARCHAR(100),
        WorkingDays NVARCHAR(100),
        StipendType NVARCHAR(50),
        StipendAmount NVARCHAR(100),
        Openings NVARCHAR(50),
        ApplicationDeadline NVARCHAR(50),
        EligibleCourses NVARCHAR(200),
        EligibleDepts NVARCHAR(200),
        PreferredSemester NVARCHAR(50),
        MinCGPA NVARCHAR(50),
        Experience NVARCHAR(50),
        RequiredSkills NVARCHAR(MAX),
        Responsibilities NVARCHAR(MAX),
        Qualifications NVARCHAR(MAX),
        Benefits NVARCHAR(MAX),
        OtherBenefits NVARCHAR(MAX),
        CompanyName NVARCHAR(200),
        CompanyLogo NVARCHAR(MAX),
        Industry NVARCHAR(100),
        CompanyLocation NVARCHAR(200),
        ContactPerson NVARCHAR(100),
        CompanyEmail NVARCHAR(100),
        CompanyWebsite NVARCHAR(200),
        Status NVARCHAR(50),
        CreatedDate DATETIME DEFAULT GETDATE()
    );
END
