//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net
{
    public partial class Students
    {
        protected global::System.Web.UI.WebControls.GridView gvStudents;
    }
}

