//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net
{


    public partial class student_profile_completion
    {

        /// <summary>
        /// litStatusHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatusHeading;

        /// <summary>
        /// litOverallPercentage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOverallPercentage;
    }
}
