//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net
{


    public partial class student_resume
    {

        /// <summary>
        /// pnlAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        /// <summary>
        /// lblAlertMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAlertMessage;

        /// <summary>
        /// pnlCurrentResume control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCurrentResume;

        /// <summary>
        /// lblCurrentFileName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentFileName;

        /// <summary>
        /// lblUploadDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUploadDate;

        /// <summary>
        /// lblFileSize control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFileSize;

        /// <summary>
        /// btnDownloadResume control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnDownloadResume;

        /// <summary>
        /// pnlNoResume control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoResume;

        /// <summary>
        /// fuResumeUpload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuResumeUpload;

        /// <summary>
        /// btnUploadResume control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUploadResume;

        /// <summary>
        /// btnConfirmDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmDelete;
    }
}
