//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp.net
{


    public partial class student_edit_profile
    {

        /// <summary>
        /// pnlAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        /// <summary>
        /// lblAlertMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAlertMessage;

        /// <summary>
        /// litCompletionPercentage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCompletionPercentage;

        /// <summary>
        /// imgProfilePreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgProfilePreview;

        /// <summary>
        /// txtInitialsFallback control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl txtInitialsFallback;

        /// <summary>
        /// fuProfilePhoto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuProfilePhoto;

        /// <summary>
        /// txtFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>
        /// rfvFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName;

        /// <summary>
        /// txtLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>
        /// rfvLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLastName;

        /// <summary>
        /// txtDOB control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDOB;

        /// <summary>
        /// ddlGender control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// revEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// rfvPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhone;

        /// <summary>
        /// txtAltPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAltPhone;

        /// <summary>
        /// txtHeadline control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHeadline;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// txtCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCity;

        /// <summary>
        /// txtState control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtState;

        /// <summary>
        /// txtCountry control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCountry;

        /// <summary>
        /// txtPincode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPincode;

        /// <summary>
        /// revPincode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPincode;

        /// <summary>
        /// txtCollege control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCollege;

        /// <summary>
        /// rfvCollege control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCollege;

        /// <summary>
        /// ddlCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;

        /// <summary>
        /// rfvCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCourse;

        /// <summary>
        /// txtBranch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBranch;

        /// <summary>
        /// ddlSemester control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSemester;

        /// <summary>
        /// txtPassingYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassingYear;

        /// <summary>
        /// txtCGPA control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCGPA;

        /// <summary>
        /// revCGPA control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revCGPA;

        /// <summary>
        /// txtCareerObjective control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCareerObjective;

        /// <summary>
        /// ddlPreferredCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPreferredCategory;

        /// <summary>
        /// txtPreferredLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPreferredLocation;

        /// <summary>
        /// ddlWorkPreference control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlWorkPreference;

        /// <summary>
        /// txtNewSkill control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewSkill;

        /// <summary>
        /// hdnSkillsList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSkillsList;

        /// <summary>
        /// lblResumeFilename control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblResumeFilename;

        /// <summary>
        /// fuResume control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuResume;

        /// <summary>
        /// txtLinkedIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLinkedIn;

        /// <summary>
        /// revLinkedIn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revLinkedIn;

        /// <summary>
        /// txtGitHub control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtGitHub;

        /// <summary>
        /// revGitHub control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revGitHub;

        /// <summary>
        /// txtPortfolio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPortfolio;

        /// <summary>
        /// revPortfolio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPortfolio;

        /// <summary>
        /// btnSaveProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
    }
}
